-- Procedures
CREATE OR REPLACE PROCEDURE AddDeliveryMethod(ID VARCHAR2, Name VARCHAR2)
AS
BEGIN
  INSERT INTO DELIVERY_METHODS (DELIVERY_METHOD_ID, DELIVERY_METHOD)
    VALUES (ID, Name);
END;
/
CREATE OR REPLACE PROCEDURE DeleteDeliveryMethod(ID VARCHAR2)
AS
BEGIN
  DELETE FROM DELIVERY_METHODS 
  WHERE DELIVERY_METHOD_ID = ID;
END;
/
CREATE OR REPLACE PROCEDURE SP_INSERT_DELIVERY_METHOD(id VARCHAR2, method VARCHAR2) AS 
BEGIN
  INSERT INTO delivery_methods
  VALUES(id, method);
END SP_INSERT_DELIVERY_METHOD;
/
CREATE OR REPLACE PROCEDURE SP_DELETE_DELIVERY_METHOD(id VARCHAR2) AS 
BEGIN
  DELETE FROM DELIVERY_METHODS
  WHERE DELIVERY_METHOD_ID = id;
END SP_DELETE_DELIVERY_METHOD;
/
CREATE OR REPLACE PROCEDURE SP_UPDATE_DELIVERY_METHOD(id VARCHAR2, method VARCHAR2) AS 
BEGIN
  UPDATE DELIVERY_METHODS
  SET DELIVERY_METHOD = method
  WHERE DELIVERY_METHOD_ID = id;
END SP_UPDATE_DELIVERY_METHOD;
/
--View compilation errors